# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korva < Formula
  desc "AI ecosystem CLI for enterprise development teams"
  homepage "https://korva.dev"
  version "1.35.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcandev/korva/releases/download/v1.35.3/korva_1.35.3_darwin_amd64.tar.gz"
      sha256 "16c410d163bc9942f521957d114c40aed85cf8554c1ace65d9eb248ded4f0869"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcandev/korva/releases/download/v1.35.3/korva_1.35.3_darwin_arm64.tar.gz"
      sha256 "c1569ef0f72c77955b8a59c97e4297bcebb6a0580411b5b32f777779b94789aa"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.35.3/korva_1.35.3_linux_amd64.tar.gz"
      sha256 "0053eb3f63f44f5d76a5551005fb2e77976904037f5ecbb004bd945149082741"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.35.3/korva_1.35.3_linux_arm64.tar.gz"
      sha256 "33976475fc80ab77b2135586d65f86cc960fbfa31722aa32fdd6c1fbe2788608"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  test do
    system "#{bin}/korva", "--version"
  end
end
