# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korva < Formula
  desc "AI ecosystem CLI for enterprise development teams"
  homepage "https://korva.dev"
  version "1.36.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcandev/korva/releases/download/v1.36.2/korva_1.36.2_darwin_amd64.tar.gz"
      sha256 "0751afe1360ed8d74329958bc7846d0f959142a3ef9563a5f783322c294cc259"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcandev/korva/releases/download/v1.36.2/korva_1.36.2_darwin_arm64.tar.gz"
      sha256 "7f5d7de0c37b49a87b57ee7997438789e5a6645cc296e5aa9f85ad1dc35b9290"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.36.2/korva_1.36.2_linux_amd64.tar.gz"
      sha256 "982280215451ff8819091dca3d8c2882f8adf118e7f9ce13f98dbf63656f5225"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.36.2/korva_1.36.2_linux_arm64.tar.gz"
      sha256 "a3641b9cf621242b6daa79039dfb8ed2981016b2589b78561f23c113bd013a90"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  test do
    system "#{bin}/korva", "--version"
  end
end
