# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korva < Formula
  desc "AI ecosystem CLI for enterprise development teams"
  homepage "https://korva.dev"
  version "1.36.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/alcandev/korva/releases/download/v1.36.3/korva_1.36.3_darwin_amd64.tar.gz"
      sha256 "6b558ed65f16944390ac0e388194429bb67dd334be0e3e87f70b10e0efdb54b9"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/alcandev/korva/releases/download/v1.36.3/korva_1.36.3_darwin_arm64.tar.gz"
      sha256 "08e3f55daa29a71236362bb4a887fec65ad7c89df5edb609e7c4de5003c9f90c"

      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.36.3/korva_1.36.3_linux_amd64.tar.gz"
      sha256 "22a5746682892cd386ca25ca8767fb7f972e4e8b62dd19120f0c5a8bef33b88e"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alcandev/korva/releases/download/v1.36.3/korva_1.36.3_linux_arm64.tar.gz"
      sha256 "0e1db7a7db68497f1ecf08ba85214474941bce2651004b0c2189dac581728969"
      define_method(:install) do
        bin.install "korva"
        bin.install "korva-vault"
        bin.install "korva-sentinel"
        bash_completion.install "completions/korva.bash" => "korva"
        zsh_completion.install "completions/korva.zsh" => "_korva"
        fish_completion.install "completions/korva.fish"
      end
    end
  end

  test do
    system "#{bin}/korva", "--version"
  end
end
